version: '3'
services:
  signal-desktop:
    image: signal-runner
    command: ["--use-tray-icon"]
    network_mode: "host"
    environment:
      - DBUS_SESSION_BUS_ADDRESS
      - DESKTOP_SESSION
      - DISPLAY
      - HTTPS_PROXY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:rw
      - /var/run/user/1000/:/var/run/user/1000/
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - ${HOME}/.Xauthority:/home/signal/.Xauthority:ro
      - ${HOME}/.config/Signal/:/home/signal/.config/Signal/
